"""post add body_html

Revision ID: 663d9efcfce6
Revises: a2a64e52bdf7
Create Date: 2016-09-02 10:13:15.698114

"""

# revision identifiers, used by Alembic.
revision = '663d9efcfce6'
down_revision = 'a2a64e52bdf7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
