"""generate token and confirm

Revision ID: 7950d39fbb04
Revises: 1e705c84d75d
Create Date: 2016-08-31 15:40:52.923634

"""

# revision identifiers, used by Alembic.
revision = '7950d39fbb04'
down_revision = '1e705c84d75d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
