"""user model add avatar_hash

Revision ID: 995e7bcccbee
Revises: c8dc9a45ac05
Create Date: 2016-09-01 15:46:22.347373

"""

# revision identifiers, used by Alembic.
revision = '995e7bcccbee'
down_revision = 'c8dc9a45ac05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
